version : '3.0'
services:
  frontend: #name of the first service
    build: frontend # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port forewarding
    container_name: front-container
    restart: always
  backend: #name of the second service
    build: backend # specify the directory of the Dockerfile
    ports:
      - "8088:8088" #specify ports forewarding
    container_name: back-container
    restart: always
    links:
      - database # link this service to the database service
  database: # name of the third service
    build: database # specify the directory of the Dockerfile
    container_name: database-container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
